server:
  port: 8080

spring:
  application:
    name: knapsackOptimizer
  data:
    mongodb:
      host: ds249428.mlab.com
      port: 49428
      database: heroku_9d4wt4cd
      username: heroku_9d4wt4cd
      password: 12drk0svu9omqv0jrbsrs1ibo7
      

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
management:
  security:
    enabled: false
    