server:
  port: 8080

spring:
  application:
    name: knapsackOptimizer
  data:
    mongodb:
      host: database-service
      port: 27017
      

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
management:
  security:
    enabled: false
    